bases:
  - ../../apps/refarch-kc/overlays

resources:
  - ./namespace.yaml
  - ./service-account.yaml
  - ./kafka-topics-configmap.yaml
  - ./bpm-configmap.yaml

secretGenerator:
# Empty value for kafka-apikey should be interpreted by consuming microservices
# that credentials are not required to connect to Kafka.
# Or maybe we can just flag this as optional?
  - name: eventstreams-apikey
    literals:
      - binding=""
  - name: postgresql-url
    literals:
      - binding="jdbc:postgresql://postgresql.postgres.svc:5432/postgres"
  - name: postgresql-user
    literals:
      - binding="postgres"
  - name: postgresql-pwd
    literals:
      - binding="supersecret"
  - name: bpm-anomaly
    literals:
      - user='your-username'
      - password='your-password'

configMapGenerator:
  - name: kafka-brokers
    literals:
      - brokers="my-cluster-kafka-bootstrap.kafka.svc:9092"

generatorOptions:
  disableNameSuffixHash: true